name: in_app_purchase_offers_example
description: An example of how to use in_app_purchase_offers.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  in_app_purchase: any
  in_app_purchase_offers:
    path: ../in_app_purchase_offers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
